### ISSUE TITLE
VanillaNetworkContextTest.networkStatsListenerShouldNotBeClosedOnBackgroundResourceReleaserThread flaky

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Network#195]
```
java.lang.AssertionError: Closeables still open
  at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:160)
  at net.openhft.chronicle.core.io.AbstractReferenceCounted.assertReferencesReleased(AbstractReferenceCounted.java:61)
  at net.openhft.chronicle.network.NetworkTestCommon.assertReferencesReleased(NetworkTestCommon.java:27)
  at net.openhft.chronicle.network.NetworkTestCommon.afterChecks(NetworkTestCommon.java:74)
  at jdk.internal.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
  Suppressed: java.lang.IllegalStateException: Not closed IdempotentLoopStartedEventHandler@1 closed=false
    at net.openhft.chronicle.core.io.AbstractCloseable.assertCloseablesClosed(AbstractCloseable.java:184)
    ... 31 more
  Caused by: net.openhft.chronicle.core.StackTrace: net.openhft.chronicle.threads.MonitorEventLoop$IdempotentLoopStartedEventHandler created here on main/testAcceptorcore-event-loop
    at net.openhft.chronicle.core.io.AbstractCloseable.<init>(AbstractCloseable.java:74)
    at net.openhft.chronicle.threads.MonitorEventLoop$IdempotentLoopStartedEventHandler.<init>(MonitorEventLoop.java:173)
    at net.openhft.chronicle.threads.MonitorEventLoop.addHandler(MonitorEventLoop.java:97)
    at net.openhft.chronicle.threads.EventGroup.addHandler(EventGroup.java:299)
    at net.openhft.chronicle.network.TcpEventHandler.eventLoop(TcpEventHandler.java:169)
    at net.openhft.chronicle.threads.VanillaEventLoop.addNewHandler(VanillaEventLoop.java:210)
    at net.openhft.chronicle.threads.MediumEventLoop.acceptNewHandlers(MediumEventLoop.java:462)
    at net.openhft.chronicle.threads.MediumEventLoop.runLoop(MediumEventLoop.java:280)
    at net.openhft.chronicle.threads.MediumEventLoop.run(MediumEventLoop.java:223)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
    at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:156)
```

**Comment by alamar** [comment]
No longer flaky
