### ISSUE TITLE
WireTcpHandlerTest fails due to heartbeat

### ISSUE THREAD

**Issue by davidjones7076** [OpenHFT/Chronicle-Network#3]
Two of the three tests in WireTcpHandlerTest fail for me with the following exception on TextWire and BinaryWire.  Cuirioulsy RawWire seems to pass without a problem.

I can workaround this by commenting out the heartbeats on WireTcpHandler.sendHeartBeat.

java.lang.UnsupportedOperationException: Unordered fields not supported yet. key=key1, was=heartbeat, data='heartbeat'
	at net.openhft.chronicle.wire.TextWire.read(TextWire.java:260)
	at net.openhft.performance.tests.network.TestData.lambda$read$5(TestData.java:46)
	at net.openhft.performance.tests.network.TestData$$Lambda$13/742394451.readMarshallable(Unknown Source)
	at net.openhft.chronicle.wire.Wires.lambda$readData$58(Wires.java:132)
	at net.openhft.chronicle.wire.Wires$$Lambda$14/1916389359.accept(Unknown Source)
	at net.openhft.chronicle.bytes.StreamingDataInput.lambda$readWithLength$1(StreamingDataInput.java:42)
	at net.openhft.chronicle.bytes.StreamingDataInput$$Lambda$15/1063288177.apply(Unknown Source)
	at net.openhft.chronicle.bytes.StreamingDataInput.parseWithLength(StreamingDataInput.java:54)
	at net.openhft.chronicle.bytes.StreamingDataInput.readWithLength(StreamingDataInput.java:41)
	at net.openhft.chronicle.wire.Wires.readData(Wires.java:132)
	at net.openhft.chronicle.wire.WireIn.readDocument(WireIn.java:82)
	at net.openhft.performance.tests.network.TestData.read(TestData.java:45)
	at net.openhft.performance.tests.network.WireTcpHandlerTest.testLatency(WireTcpHandlerTest.java:113)
	at net.openhft.performance.tests.network.WireTcpHandlerTest.testProcess(WireTcpHandlerTest.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runners.Suite.runChild(Suite.java:127)
	at org.junit.runners.Suite.runChild(Suite.java:26)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by davidjones7076** [comment]
Not seen a response on this.  Is there somewhere else I should be posting issues like this ?

**Comment by RobAustin** [comment]
Could you retest with the latest version. It's possible this has now been fixed ( as we fixed something similar to this over the weekend )

**Comment by davidjones7076** [comment]
Rob - thanks for coming back on this.

A retest after an update shows the first two tests failing, but the third passing.  The first two tests fail with the same stack trace.  Again, commenting out the heartbeat resolves the issue.

I added a catch for the USO exception around the read in the WireTcpHandlerTest and logged the inBytes hex string as per the below to try and see what was causing the exception.
```java
try {
  td2.read(inWire);
}
catch (UnsupportedOperationException ex) {
  System.out.printf("Exception%n%s%n", inBytes.toHexString());
}
```

As expected, you can see a heartbeat message prepending an encoded message which then trips up the Wire decoder.
```
00000020 38 31 38 38 38 34 34 0A  23 00 00 00 6B 65 79 31 8188844· #···key1
00000030 3A 20 33 33 32 38 0A 6B  65 79 32 3A 20 33 33 32 : 3328·k ey2: 332
00000040 38 0A 6B 65 79 33 3A 20  33 33 32 38 2E 30 0A    8·key3:  3328.0· 
```

If I add more logging to slow down the test then they all pass, so it looks like a race condition whereby heartbeats aren't consumed before our reader attempts to decode a message.

Let me know any suggestions you may have on this.  I haven't fully done my homework on the heartbeat handling logic in the TcpEventHandler yet, but will start taking a look.

**Comment by RobAustin** [comment]
I think- heart-beating got added to the server but the test was not updated to reflect this. It was fixed this morning, if you update to the latest snapshot, you should be able to get this fix, or you can pick up the fix in the next release. By the way, although the test was failing which was not good ( there was not a bug in the code), it was just the test was a bit out of date. The resolution was to allow the test to config the heartbeat period specifying zero as no heart-beating ( and update the code to allow for this )

**Comment by RobAustin** [comment]
can you close this issue if it fixes the problem - thanks

**Comment by davidjones7076** [comment]
Excellent.  Re-updated to the snapshot and I can see it now passes.

I'll close this issue.

BTW, is there an active forum for Chronicle-Network as I'd like to ask a question around extending the WireTcpHandlerTest with a throughput test ?  Previous attempts to do this were slow as the WireTcpHandler will only process a single msg at a time.

**Comment by RobAustin** [comment]
> is there an active forum for Chronicle-Network
yes,  java-chronicle@googlegroups.com

Regarding
> "Previous attempts to do this were slow as the WireTcpHandler will only process a single msg at a time" 

I've added functionality yesterday to support concurrent WireTcpHandler wire processing,( only available in the snapshot ) in short, set 

-DServerThreadingStrategy=MULTI_THREADED_BUSY_WAITING

I'll provide a bit more detail around this in the readme tomorrow as I only implemented it yesterday, but if you are able to test it an give me some feedback that would be great.

Rob Austin

**Comment by davidjones7076** [comment]
Thanks for the Google group.

Will definitely take a look and give you some feedback.  I'd had in my mind that using the "smart batching" approach would be a good addition for inbound and outbound flow to maximise throughput.
