### ISSUE TITLE
A network client attempts to reconnect when closing.

### ISSUE THREAD

**Issue by peter-lawrey** [OpenHFT/Chronicle-Network#31]
When the client is closed it calls a listener which attempt to re-opne the connection.

[main/event-loop-monitor] INFO software.chronicle.runner.v2.Monitor - 
	at net.openhft.chronicle.wire.BinaryWire.write(BinaryWire.java:1031)
	at net.openhft.chronicle.network.cluster.handlers.UberHandler.writeMarshallable(UberHandler.java:88)
	at net.openhft.chronicle.wire.BinaryWire$FixedBinaryValueOut.marshallable(BinaryWire.java:1721)
	at net.openhft.chronicle.wire.ValueOut.typedMarshallable(ValueOut.java:420)
	at net.openhft.chronicle.network.cluster.handlers.UberHandler.lambda$uberHandler$5(UberHandler.java:64)
	at net.openhft.chronicle.network.cluster.handlers.UberHandler$$Lambda$229/1711639613.writeMarshallable(Unknown Source)
	at net.openhft.chronicle.network.connection.VanillaWireOutPublisher.put(VanillaWireOutPublisher.java:175)
	at net.openhft.chronicle.network.connection.WireOutPublisher.publish(WireOutPublisher.java:114)
	at net.openhft.chronicle.network.cluster.HostConnector.connect(HostConnector.java:118)
	at net.openhft.chronicle.network.cluster.HostConnector.reconnect(HostConnector.java:130)
	at net.openhft.chronicle.network.cluster.ClusterNotifier.onClose(ClusterNotifier.java:66)
	at net.openhft.chronicle.network.cluster.ClusterNotifier.onConnectionChanged(ClusterNotifier.java:54)
	at net.openhft.chronicle.network.cluster.handlers.UberHandler.close(UberHandler.java:189)
	at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:42)
	at net.openhft.chronicle.network.TcpEventHandler.closeSC(TcpEventHandler.java:367)
	at net.openhft.chronicle.network.TcpEventHandler.close(TcpEventHandler.java:361)
	at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:42)
	at net.openhft.chronicle.threads.VanillaEventLoop.lambda$closeAll$0(VanillaEventLoop.java:118)
	at net.openhft.chronicle.threads.VanillaEventLoop$$Lambda$390/972152147.accept(Unknown Source)
	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
	at net.openhft.chronicle.threads.VanillaEventLoop.closeAll(VanillaEventLoop.java:116)
	at net.openhft.chronicle.threads.VanillaEventLoop.closeAllHandlers(VanillaEventLoop.java:508)
	at net.openhft.chronicle.threads.VanillaEventLoop.close(VanillaEventLoop.java:461)
	at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:42)
	at net.openhft.chronicle.core.io.Closeable$$Lambda$388/1091202270.accept(Unknown Source)

**Comment by dpisklov** [comment]
What is the expected behaviour? Shall we cancel reconnect logic upon closing the cluster?

**Comment by RobAustin** [comment]
Until it has been *terminated* a call to close(), will attempt to close the existing connection and re-establish a new connection.
