### ISSUE TITLE
deadlock upon shutdown

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Network#93]
Full stack trace looks like this:

2020-11-30 16:37:29
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.231-b11 mixed mode):

"main/queue-cluster-3-acceptor-3" #25 prio=5 os_prio=0 tid=0x000000001f296800 nid=0xfbc runnable [0x000000002290e000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        - locked <0x00000006c37cec78> (a java.lang.Object)
        at net.openhft.chronicle.network.tcp.VanillaChronicleServerSocketChannel.accept(VanillaChronicleServerSocketChannel.java:28)
        at net.openhft.chronicle.network.cluster.ClusterAcceptorEventHandler.action(ClusterAcceptorEventHandler.java:55)
        at net.openhft.chronicle.threads.BlockingEventLoop$Runner.run(BlockingEventLoop.java:174)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:67)

"main/queue-cluster-3-~monitor" #24 daemon prio=5 os_prio=0 tid=0x000000001f292800 nid=0x7a48 waiting on condition [0x000000002280f000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at net.openhft.chronicle.core.Jvm.pause(Jvm.java:381)
        at net.openhft.chronicle.threads.MilliPauser.doPauseMS(MilliPauser.java:67)
        at net.openhft.chronicle.threads.MilliPauser.pause(MilliPauser.java:61)
        at net.openhft.chronicle.threads.MonitorEventLoop.run(MonitorEventLoop.java:126)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:67)

"main/queue-cluster-3-blocking-event-loop-1" #23 prio=5 os_prio=0 tid=0x000000001f292000 nid=0x23f4 runnable [0x000000002270e000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.Net.connect0(Native Method)
        at sun.nio.ch.Net.connect(Net.java:454)
        at sun.nio.ch.Net.connect(Net.java:446)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)
        - locked <0x000000076c3d9ba8> (a java.lang.Object)
        - locked <0x000000076c3d9bc8> (a java.lang.Object)
        - locked <0x000000076c3d9bb8> (a java.lang.Object)
        at java.nio.channels.SocketChannel.open(SocketChannel.java:189)
        at net.openhft.chronicle.network.tcp.ChronicleSocketChannelFactory.wrap(ChronicleSocketChannelFactory.java:26)
        at net.openhft.chronicle.network.RemoteConnector.openSocketChannel(RemoteConnector.java:94)
        at net.openhft.chronicle.network.RemoteConnector$RCEventHandler.action(RemoteConnector.java:160)
        at net.openhft.chronicle.threads.BlockingEventLoop$Runner.run(BlockingEventLoop.java:174)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:67)

"main/queue-cluster-3-core-event-loop" #21 daemon prio=5 os_prio=0 tid=0x000000001f28f800 nid=0x63f8 waiting on condition [0x000000002250e000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at net.openhft.chronicle.core.Jvm.pause(Jvm.java:381)
        at net.openhft.chronicle.threads.LongPauser.doPause(LongPauser.java:137)
        at net.openhft.chronicle.threads.LongPauser.pause(LongPauser.java:88)
        at net.openhft.chronicle.threads.MediumEventLoop.runLoop(MediumEventLoop.java:295)
        at net.openhft.chronicle.threads.MediumEventLoop.run(MediumEventLoop.java:236)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:67)

"main/queue-cluster-2-acceptor-2" #20 prio=5 os_prio=0 tid=0x000000001f283800 nid=0x7c18 runnable [0x0000000021aee000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
        at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
        - locked <0x00000006c37ee000> (a java.lang.Object)
        at net.openhft.chronicle.network.tcp.VanillaChronicleServerSocketChannel.accept(VanillaChronicleServerSocketChannel.java:28)
        at net.openhft.chronicle.network.cluster.ClusterAcceptorEventHandler.action(ClusterAcceptorEventHandler.java:55)
        at net.openhft.chronicle.threads.BlockingEventLoop$Runner.run(BlockingEventLoop.java:174)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:67)

"main/queue-cluster-2-~monitor" #19 daemon prio=5 os_prio=0 tid=0x000000001f27c000 nid=0x6df4 waiting on condition [0x00000000219ee000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(Native Method)
        at net.openhft.chronicle.core.Jvm.pause(Jvm.java:381)
        at net.openhft.chronicle.threads.MilliPauser.doPauseMS(MilliPauser.java:67)
        at net.openhft.chronicle.threads.MilliPauser.pause(MilliPauser.java:61)
        at net.openhft.chronicle.threads.MonitorEventLoop.run(MonitorEventLoop.java:126)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:67)

"main/queue-cluster-2-core-event-loop" #17 daemon prio=5 os_prio=0 tid=0x000000001f27a800 nid=0x7078 waiting for monitor entry [0x00000000217ef000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at net.openhft.chronicle.network.cluster.ClusterContext.eventLoop(ClusterContext.java:130)
        - waiting to lock <0x00000006c384fbe0> (a software.chronicle.enterprise.queue.replication.QueueClusterContext)
        at net.openhft.chronicle.network.cluster.VanillaClusteredNetworkContext.<init>(VanillaClusteredNetworkContext.java:22)
        at software.chronicle.enterprise.queue.replication.QueueClusterNetworkContext.<init>(QueueClusterNetworkContext.java:27)
        at software.chronicle.enterprise.queue.replication.QueueClusterNetworkContext$Factory.apply(QueueClusterNetworkContext.java:88)
        at software.chronicle.enterprise.queue.replication.QueueClusterNetworkContext$Factory.apply(QueueClusterNetworkContext.java:83)
        at net.openhft.chronicle.network.cluster.HostConnector.connect(HostConnector.java:108)
        - locked <0x00000006c384f658> (a net.openhft.chronicle.network.cluster.HostConnector)
        at net.openhft.chronicle.network.cluster.HostConnector.reconnect(HostConnector.java:138)
        - locked <0x00000006c384f658> (a net.openhft.chronicle.network.cluster.HostConnector)
        at net.openhft.chronicle.network.cluster.HostConnector$$Lambda$152/226744878.run(Unknown Source)
        at net.openhft.chronicle.network.TcpEventHandler.readAction(TcpEventHandler.java:282)
        at net.openhft.chronicle.network.TcpEventHandler.action0(TcpEventHandler.java:212)
        at net.openhft.chronicle.network.TcpEventHandler.action(TcpEventHandler.java:186)
        at net.openhft.chronicle.threads.MediumEventLoop.runAllMediumHandler(MediumEventLoop.java:354)
        at net.openhft.chronicle.threads.MediumEventLoop.runLoop(MediumEventLoop.java:270)
        at net.openhft.chronicle.threads.MediumEventLoop.run(MediumEventLoop.java:236)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:67)

"background~resource~releaser" #12 daemon prio=5 os_prio=0 tid=0x000000001f32c000 nid=0x692c waiting on condition [0x000000001fa0e000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000006c37cf3b8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
        at net.openhft.chronicle.core.io.BackgroundResourceReleaser.runReleaseResources(BackgroundResourceReleaser.java:27)
        at net.openhft.chronicle.core.io.BackgroundResourceReleaser$$Lambda$11/1018937824.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:748)

"Service Thread" #11 daemon prio=9 os_prio=0 tid=0x000000001ddd0800 nid=0x2f20 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread3" #10 daemon prio=9 os_prio=2 tid=0x000000001dd38000 nid=0x1a1c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread2" #9 daemon prio=9 os_prio=2 tid=0x000000001dd2c000 nid=0x6ac waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #8 daemon prio=9 os_prio=2 tid=0x000000001dd20800 nid=0x5a7c waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #7 daemon prio=9 os_prio=2 tid=0x000000001dd1c000 nid=0x45f4 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Monitor Ctrl-Break" #6 daemon prio=5 os_prio=0 tid=0x000000001dd25800 nid=0x81d0 runnable [0x000000001e68e000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        - locked <0x00000006c37d5918> (a java.io.InputStreamReader)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        - locked <0x00000006c37d5918> (a java.io.InputStreamReader)
        at java.io.BufferedReader.readLine(BufferedReader.java:389)
        at com.intellij.rt.execution.application.AppMainV2$1.run(AppMainV2.java:64)

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x000000001dcc1800 nid=0x1278 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x000000001dcc0000 nid=0x5364 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x000000001dcb1800 nid=0x7b94 in Object.wait() [0x000000001e28e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000006c37dead0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
        - locked <0x00000006c37dead0> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x000000001dcb0800 nid=0x4900 in Object.wait() [0x000000001e18f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000006c37bf7e0> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x00000006c37bf7e0> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00000000022ee800 nid=0x52fc waiting for monitor entry [0x00000000022bd000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at net.openhft.chronicle.network.cluster.HostConnector.close(HostConnector.java:75)
        - waiting to lock <0x00000006c384f658> (a net.openhft.chronicle.network.cluster.HostConnector)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:44)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:40)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:40)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:32)
        at net.openhft.chronicle.network.cluster.ClusterContext.performClose(ClusterContext.java:300)
        - locked <0x00000006c384fbe0> (a software.chronicle.enterprise.queue.replication.QueueClusterContext)
        at net.openhft.chronicle.network.cluster.ClusterContext.close(ClusterContext.java:296)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:44)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:40)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:32)
        at net.openhft.chronicle.network.cluster.Cluster.performClose(Cluster.java:106)
        at net.openhft.chronicle.core.io.SimpleCloseable.close(SimpleCloseable.java:34)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:44)
        at net.openhft.chronicle.core.io.Closeable$$Lambda$105/770911223.accept(Unknown Source)
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:37)
        at software.chronicle.enterprise.queue.replication.ReplicatedQueue.performClose(ReplicatedQueue.java:246)
        at net.openhft.chronicle.core.io.SimpleCloseable.close(SimpleCloseable.java:34)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:44)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest$Replicator.stop(ReplicationFailbackTest.java:332)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest.lambda$runTest$0(ReplicationFailbackTest.java:179)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest$$Lambda$237/71399214.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest.withServices(ReplicationFailbackTest.java:279)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest.runTest(ReplicationFailbackTest.java:179)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest.test(ReplicationFailbackTest.java:145)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
        at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

"VM Thread" os_prio=2 tid=0x000000001beb9800 nid=0x6998 runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x0000000002459000 nid=0x30e0 runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x000000000245a800 nid=0x7fd0 runnable

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x000000000245c000 nid=0x15bc runnable

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x000000000245d800 nid=0x3978 runnable

"GC task thread#4 (ParallelGC)" os_prio=0 tid=0x0000000002460000 nid=0x8808 runnable

"GC task thread#5 (ParallelGC)" os_prio=0 tid=0x0000000002462000 nid=0x6c90 runnable

"GC task thread#6 (ParallelGC)" os_prio=0 tid=0x0000000002465800 nid=0x82a0 runnable

"GC task thread#7 (ParallelGC)" os_prio=0 tid=0x0000000002466800 nid=0x36b0 runnable

"VM Periodic Task Thread" os_prio=2 tid=0x000000001ddfd000 nid=0x19d8 waiting on condition

JNI global references: 758

Found one Java-level deadlock:
=============================
"main/queue-cluster-2-core-event-loop":
  waiting to lock monitor 0x000000001f2c4ee8 (object 0x00000006c384fbe0, a software.chronicle.enterprise.queue.replication.QueueClusterContext),
  which is held by "main"
"main":
  waiting to lock monitor 0x000000000253cfc8 (object 0x00000006c384f658, a net.openhft.chronicle.network.cluster.HostConnector),
  which is held by "main/queue-cluster-2-core-event-loop"

Java stack information for the threads listed above:
===================================================
"main/queue-cluster-2-core-event-loop":
        at net.openhft.chronicle.network.cluster.ClusterContext.eventLoop(ClusterContext.java:130)
        - waiting to lock <0x00000006c384fbe0> (a software.chronicle.enterprise.queue.replication.QueueClusterContext)
        at net.openhft.chronicle.network.cluster.VanillaClusteredNetworkContext.<init>(VanillaClusteredNetworkContext.java:22)
        at software.chronicle.enterprise.queue.replication.QueueClusterNetworkContext.<init>(QueueClusterNetworkContext.java:27)
        at software.chronicle.enterprise.queue.replication.QueueClusterNetworkContext$Factory.apply(QueueClusterNetworkContext.java:88)
        at software.chronicle.enterprise.queue.replication.QueueClusterNetworkContext$Factory.apply(QueueClusterNetworkContext.java:83)
        at net.openhft.chronicle.network.cluster.HostConnector.connect(HostConnector.java:108)
        - locked <0x00000006c384f658> (a net.openhft.chronicle.network.cluster.HostConnector)
        at net.openhft.chronicle.network.cluster.HostConnector.reconnect(HostConnector.java:138)
        - locked <0x00000006c384f658> (a net.openhft.chronicle.network.cluster.HostConnector)
        at net.openhft.chronicle.network.cluster.HostConnector$$Lambda$152/226744878.run(Unknown Source)
        at net.openhft.chronicle.network.TcpEventHandler.readAction(TcpEventHandler.java:282)
        at net.openhft.chronicle.network.TcpEventHandler.action0(TcpEventHandler.java:212)
        at net.openhft.chronicle.network.TcpEventHandler.action(TcpEventHandler.java:186)
        at net.openhft.chronicle.threads.MediumEventLoop.runAllMediumHandler(MediumEventLoop.java:354)
        at net.openhft.chronicle.threads.MediumEventLoop.runLoop(MediumEventLoop.java:270)
        at net.openhft.chronicle.threads.MediumEventLoop.run(MediumEventLoop.java:236)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
        at net.openhft.chronicle.core.threads.CleaningThread.run(CleaningThread.java:67)
"main":
        at net.openhft.chronicle.network.cluster.HostConnector.close(HostConnector.java:75)
        - waiting to lock <0x00000006c384f658> (a net.openhft.chronicle.network.cluster.HostConnector)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:44)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:40)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:40)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:32)
        at net.openhft.chronicle.network.cluster.ClusterContext.performClose(ClusterContext.java:300)
        - locked <0x00000006c384fbe0> (a software.chronicle.enterprise.queue.replication.QueueClusterContext)
        at net.openhft.chronicle.network.cluster.ClusterContext.close(ClusterContext.java:296)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:44)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:40)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:32)
        at net.openhft.chronicle.network.cluster.Cluster.performClose(Cluster.java:106)
        at net.openhft.chronicle.core.io.SimpleCloseable.close(SimpleCloseable.java:34)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:44)
        at net.openhft.chronicle.core.io.Closeable$$Lambda$105/770911223.accept(Unknown Source)
        at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:37)
        at software.chronicle.enterprise.queue.replication.ReplicatedQueue.performClose(ReplicatedQueue.java:246)
        at net.openhft.chronicle.core.io.SimpleCloseable.close(SimpleCloseable.java:34)
        at net.openhft.chronicle.core.io.Closeable.closeQuietly(Closeable.java:44)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest$Replicator.stop(ReplicationFailbackTest.java:332)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest.lambda$runTest$0(ReplicationFailbackTest.java:179)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest$$Lambda$237/71399214.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
        at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest.withServices(ReplicationFailbackTest.java:279)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest.runTest(ReplicationFailbackTest.java:179)
        at software.chronicle.enterprise.queue.test.ReplicationFailbackTest.test(ReplicationFailbackTest.java:145)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
        at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
        at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
        at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

Found 1 deadlock.

**Comment by RobAustin** [comment]
fixed in this commit https://github.com/OpenHFT/Chronicle-Network/commit/dcb348f957e435a8be890a30e4f87bd680dbf497
